RESET ROLE;

CREATE SCHEMA zbi_data
    AUTHORIZATION zalando;

GRANT USAGE ON SCHEMA zbi_data TO zalando_data_usage;

ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data GRANT EXECUTE ON FUNCTIONS TO zalando_data_writer;

ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data GRANT USAGE ON SEQUENCES TO zalando_data_writer;
ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data GRANT SELECT ON SEQUENCES TO zalando_data_reader;

ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data GRANT SELECT ON TABLES TO zalando_data_reader;
ALTER DEFAULT PRIVILEGES FOR ROLE zalando IN SCHEMA zbi_data GRANT INSERT, DELETE, UPDATE ON TABLES TO zalando_data_writer;

SET role TO zalando;

