RESET ROLE;

CREATE SCHEMA __SCHEMA__
    AUTHORIZATION __MAIN_ROLE__;

GRANT USAGE ON SCHEMA __SCHEMA__ TO __DATA_USAGE_ROLE__;

ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ GRANT EXECUTE ON FUNCTIONS TO __WRITE_ROLE__;

ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ GRANT USAGE ON SEQUENCES TO __WRITE_ROLE__;
ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ GRANT SELECT ON SEQUENCES TO __READ_ROLE__;

ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ GRANT SELECT ON TABLES TO __READ_ROLE__;
ALTER DEFAULT PRIVILEGES FOR ROLE __MAIN_ROLE__ IN SCHEMA __SCHEMA__ GRANT INSERT, DELETE, UPDATE ON TABLES TO __WRITE_ROLE__;

SET role TO __MAIN_ROLE__;

